<template>
  <section class="banner" id="home">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="banner-text">
            <h1>{{ title }}</h1>
            <p>{{ subtitle }}</p>
            <a href="#" class="btn btn-primary">{{ button }}</a>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>
<script>
export default {};
</script>
